version: '3.8'

services:
  image-analyzer:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
